// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SolarStore.Data;

#nullable disable

namespace SolarStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SolarStore.Models.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                b.Property<int>("OrderId").HasColumnType("integer");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<decimal>("UnitPrice").HasColumnType("numeric(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.HasIndex("ProductId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("SolarStore.Models.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                b.Property<DateTime>("OrderDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Notes").HasColumnType("text");
                b.Property<string>("ShippingAddress").IsRequired().HasColumnType("text");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<decimal>("TotalAmount").HasColumnType("numeric(18,2)");
                b.Property<int>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("SolarStore.Models.Product", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                b.Property<string>("Category").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("ImageUrl").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<decimal>("Price").HasColumnType("numeric(18,2)");
                b.Property<int>("Stock").HasColumnType("integer");
                b.HasKey("Id");
                b.ToTable("Products");
            });

            modelBuilder.Entity("SolarStore.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("SolarStore.Models.OrderItem", b =>
            {
                b.HasOne("SolarStore.Models.Order", "Order")
                    .WithMany("OrderItems").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("SolarStore.Models.Product", "Product")
                    .WithMany("OrderItems").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("SolarStore.Models.Order", b =>
            {
                b.HasOne("SolarStore.Models.User", "User")
                    .WithMany("Orders").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
